export const __INIT__ = '__INIT__'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_ERROR = 'FETCH_ERROR'
export const UPDATE_ITEMS = 'UPDATE_ITEMS'
export const UPDATE_ERROR = 'UPDATE_ERROR'
